[bug][storage] Make ES-Rollover idempotent by checking if the index or alias already exist (#6638)
## Which problem is this PR solving?
Fixes: #6203 

## Description of the changes
- Currently `es-rollover` checks for index existence through errors, it
is mainly expecting the error:
```
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"]"}],"type":"resource_already_exists_exception","reason":"request [/jaeger-*] contains unrecognized parameter: [help]"},"status":400}
```
But it can lead to inconsistent results as found in the issue, where
init was failing due to the error:
```
Error: failed to create index: jaeger-span-000001, request failed, status code: 400, body: {"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [jaeger-span-000001], already exists as alias","index_uuid":"_na_","index":"jaeger-span-000001"}],"type":"invalid_index_name_exception","reason":"Invalid index name [jaeger-span-000001], already exists as alias","index_uuid":"_na_","index":"jaeger-span-000001"},"status":400}
``` 
Here if we see carefully the error is coming due to existence of index
but the reason is different. `es-rollover` is ready only for
`resource_already_exists_exception` but there are other errors also
which can be generated due to this (like the above).

The current way of marshalling error is unsafe, the safe way is: Check
if index exists -> Create if not exists. This way the certained error
(`resource_already_exists` is fixed) and the unavoidable error like
`index_name_exception` is ignored.

## How was this change tested?
- Unit and E2E Tests

## Checklist
- [x] I have read
https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `npm run lint` and `npm run test`

---------

Signed-off-by: Manik2708 <mehtamanik96@gmail.com>