Fix release script broken by recent linting cleanup (#4915)
## Which problem is this PR solving?
```
Run bash scripts/package-deploy.sh
+ set -e
+ readonly VERSION
++ make echo-version
++ perl -lne 'print $1 if /^v(\d+.\d+.\d+)$/'
+ VERSION=1.51.0
scripts/package-deploy.sh: line 55: VERSION: readonly variable
Error: Process completed with exit code 1.
```
## Description of the changes
- remove `readonly` declaration

## How was this change tested?
- will rerun script after merging, no other way to test

Signed-off-by: Yuri Shkuro <github@ysh.us>