Update opensearchproject/opensearch Docker tag to v3.1.0 (#7379)
This PR contains the following updates:

| Package | Update | Change |
|---|---|---|
|
[opensearchproject/opensearch](https://redirect.github.com/opensearch-project/OpenSearch)
| minor | `3.0.0` -> `3.1.0` |
|
[opensearchproject/opensearch](https://redirect.github.com/opensearch-project/OpenSearch)
| major | `2.19.0` -> `3.1.0` |

---

### Release Notes

<details>
<summary>opensearch-project/OpenSearch
(opensearchproject/opensearch)</summary>

###
[`v3.1.0`](https://redirect.github.com/opensearch-project/OpenSearch/releases/tag/3.1.0)

[Compare
Source](https://redirect.github.com/opensearch-project/OpenSearch/compare/3.0.0...3.1.0)

#### 2025-06-17 Version 3.1.0 Release Notes

#### \[3.1]

##### Added

- Add support for linux riscv64 platform
([#&#8203;18156](https://redirect.github.com/opensearch-project/OpenSearch/pull/18156))
- \[Rule based auto-tagging] Add get rule API
([#&#8203;17336](https://redirect.github.com/opensearch-project/OpenSearch/pull/17336))
- \[Rule based auto-tagging] Add Delete Rule API
([#&#8203;18184](https://redirect.github.com/opensearch-project/OpenSearch/pull/18184))
- Add paginated wlm/stats API
([#&#8203;17638](https://redirect.github.com/opensearch-project/OpenSearch/pull/17638))
- \[Rule based auto-tagging] Add Create rule API
([#&#8203;17792](https://redirect.github.com/opensearch-project/OpenSearch/pull/17792))
- Implement parallel shard refresh behind cluster settings
([#&#8203;17782](https://redirect.github.com/opensearch-project/OpenSearch/pull/17782))
- Bump OpenSearch Core main branch to 3.0.0
([#&#8203;18039](https://redirect.github.com/opensearch-project/OpenSearch/pull/18039))
- \[Rule based Auto-tagging] Add wlm `ActionFilter`
([#&#8203;17791](https://redirect.github.com/opensearch-project/OpenSearch/pull/17791))
- \[Rule based auto-tagging] Add update rule API
([#&#8203;17797](https://redirect.github.com/opensearch-project/OpenSearch/pull/17797))
- \[Rule based auto-tagging] Bug fix for update rule api
([#&#8203;18488](https://redirect.github.com/opensearch-project/OpenSearch/pull/18488))
- Update API of Message in index to add the timestamp for lag
calculation in ingestion polling
([#&#8203;17977](https://redirect.github.com/opensearch-project/OpenSearch/pull/17977/))
- Add Warm Disk Threshold Allocation Decider for Warm shards
([#&#8203;18082](https://redirect.github.com/opensearch-project/OpenSearch/pull/18082))
- Add composite directory factory
([#&#8203;17988](https://redirect.github.com/opensearch-project/OpenSearch/pull/17988))
- \[Rule based auto-tagging] Add refresh based synchronization service
for `Rule`s
([#&#8203;18128](https://redirect.github.com/opensearch-project/OpenSearch/pull/18128))
- Add pull-based ingestion error metrics and make internal queue size
configurable
([#&#8203;18088](https://redirect.github.com/opensearch-project/OpenSearch/pull/18088))
- Adding support for derive source feature and implementing it for
various type of field mappers
([#&#8203;17759](https://redirect.github.com/opensearch-project/OpenSearch/pull/17759))
- \[Security Manager Replacement] Enhance Java Agent to intercept
newByteChannel
([#&#8203;17989](https://redirect.github.com/opensearch-project/OpenSearch/pull/17989))
- Enabled Async Shard Batch Fetch by default
([#&#8203;18139](https://redirect.github.com/opensearch-project/OpenSearch/pull/18139))
- Allow to get the search request from the QueryCoordinatorContext
([#&#8203;17818](https://redirect.github.com/opensearch-project/OpenSearch/pull/17818))
- Reject close index requests, while remote store migration is in
progress.([#&#8203;18327](https://redirect.github.com/opensearch-project/OpenSearch/pull/18327))
- Improve sort-query performance by retaining the default
`totalHitsThreshold` for approximated `match_all` queries
([#&#8203;18189](https://redirect.github.com/opensearch-project/OpenSearch/pull/18189))
- Enable testing for ExtensiblePlugins using classpath plugins
([#&#8203;16908](https://redirect.github.com/opensearch-project/OpenSearch/pull/16908))
- Introduce system generated ingest pipeline
([#&#8203;17817](https://redirect.github.com/opensearch-project/OpenSearch/pull/17817)))
- Added Auto Force Merge Manager to enhance hot to warm migration
experience
([#&#8203;18229](https://redirect.github.com/opensearch-project/OpenSearch/pull/18229))
- Apply cluster state metadata and routing table diff when building
cluster state from
remote([#&#8203;18256](https://redirect.github.com/opensearch-project/OpenSearch/pull/18256))
- Support create mode in pull-based ingestion and add retries for
transient failures
([#&#8203;18250](https://redirect.github.com/opensearch-project/OpenSearch/pull/18250)))
- Decouple the init of Crypto Plugin and KeyProvider in CryptoRegistry
([18270](https://redirect.github.com/opensearch-project/OpenSearch/pull18270)))
- Support cluster write block in pull-based ingestion
([#&#8203;18280](https://redirect.github.com/opensearch-project/OpenSearch/pull/18280)))
- Use QueryCoordinatorContext for the rewrite in validate API.
([#&#8203;18272](https://redirect.github.com/opensearch-project/OpenSearch/pull/18272))
- Upgrade crypto kms plugin dependencies for AWS SDK v2.x.
([#&#8203;18268](https://redirect.github.com/opensearch-project/OpenSearch/pull/18268))
- Add support for `matched_fields` with the unified highlighter
([#&#8203;18164](https://redirect.github.com/opensearch-project/OpenSearch/issues/18164))
- Add BooleanQuery rewrite for must\_not RangeQuery clauses
([#&#8203;17655](https://redirect.github.com/opensearch-project/OpenSearch/pull/17655))
- \[repository-s3] Add support for SSE-KMS and S3 bucket owner
verification
([#&#8203;18312](https://redirect.github.com/opensearch-project/OpenSearch/pull/18312))
- Optimize gRPC perf by passing by reference
([#&#8203;18303](https://redirect.github.com/opensearch-project/OpenSearch/pull/18303))
- Added File Cache Stats - Involves Block level as well as full file
level stats
([#&#8203;17538](https://redirect.github.com/opensearch-project/OpenSearch/issues/17479))
- Added time\_in\_execution attribute to /\_cluster/pending\_tasks
response
([#&#8203;17780](https://redirect.github.com/opensearch-project/OpenSearch/pull/17780))
- Added File Cache Pinning
([#&#8203;17617](https://redirect.github.com/opensearch-project/OpenSearch/issues/13648))
- Support consumer reset in Resume API for pull-based ingestion. This PR
includes a breaking change for the experimental pull-based ingestion
feature.
([#&#8203;18332](https://redirect.github.com/opensearch-project/OpenSearch/pull/18332))
- Add FIPS build tooling
([#&#8203;4254](https://redirect.github.com/opensearch-project/security/issues/4254))
- Support Nested Aggregations as part of Star-Tree
([#&#8203;18048](https://redirect.github.com/opensearch-project/OpenSearch/pull/18048))
- \[Star-Tree] Support for date-range queries with star-tree supported
aggregations
([#&#8203;17855](https://redirect.github.com/opensearch-project/OpenSearch/pull/17855)
- Added node-left metric to cluster manager
([#&#8203;18421](https://redirect.github.com/opensearch-project/OpenSearch/pull/18421))
- \[Star tree] Remove star tree feature flag and add index setting to
configure star tree search on index basis
([#&#8203;18070](https://redirect.github.com/opensearch-project/OpenSearch/pull/18070))
- Approximation Framework Enhancement: Update the BKD traversal logic to
improve the performance on skewed data
([#&#8203;18439](https://redirect.github.com/opensearch-project/OpenSearch/issues/18439))
- Support system generated ingest pipelines for bulk update operations
([#&#8203;18277](https://redirect.github.com/opensearch-project/OpenSearch/pull/18277)))
- Added FS Health Check Failure metric
([#&#8203;18435](https://redirect.github.com/opensearch-project/OpenSearch/pull/18435))

##### Changed

- Create generic DocRequest to better categorize ActionRequests
([#&#8203;18269](https://redirect.github.com/opensearch-project/OpenSearch/pull/18269)))
- Change implementation for `percentiles` aggregation for latency
improvement
([#&#8203;18124](https://redirect.github.com/opensearch-project/OpenSearch/pull/18124))
- Update FipsMode check to catch NoSuchMethodError
([#&#8203;18427](https://redirect.github.com/opensearch-project/OpenSearch/pull/18427))

##### Dependencies

- Update Apache Lucene from 10.1.0 to 10.2.1
([#&#8203;17961](https://redirect.github.com/opensearch-project/OpenSearch/pull/17961))
- Bump `com.google.code.gson:gson` from 2.12.1 to 2.13.1
([#&#8203;17923](https://redirect.github.com/opensearch-project/OpenSearch/pull/17923),
[#&#8203;18266](https://redirect.github.com/opensearch-project/OpenSearch/pull/18266))
- Bump `com.github.spotbugs:spotbugs-annotations` from 4.9.0 to 4.9.3
([#&#8203;17922](https://redirect.github.com/opensearch-project/OpenSearch/pull/17922))
- Bump `com.microsoft.azure:msal4j` from 1.18.0 to 1.20.0
([#&#8203;17925](https://redirect.github.com/opensearch-project/OpenSearch/pull/17925))
- Update Apache HttpClient5 and HttpCore5 (CVE-2025-27820)
([#&#8203;18152](https://redirect.github.com/opensearch-project/OpenSearch/pull/18152))
- Bump `org.apache.commons:commons-collections4` from 4.4 to 4.5.0
([#&#8203;18101](https://redirect.github.com/opensearch-project/OpenSearch/pull/18101))
- Bump `netty` from 4.1.118.Final to 4.1.121.Final
([#&#8203;18192](https://redirect.github.com/opensearch-project/OpenSearch/pull/18192))
- Bump `org.apache.commons:commons-configuration2` from 2.11.0 to 2.12.0
([#&#8203;18103](https://redirect.github.com/opensearch-project/OpenSearch/pull/18103),
[#&#8203;18262](https://redirect.github.com/opensearch-project/OpenSearch/pull/18262))
- Bump `com.nimbusds:nimbus-jose-jwt` from 10.0.2 to 10.3
([#&#8203;18104](https://redirect.github.com/opensearch-project/OpenSearch/pull/18104),
[#&#8203;18336](https://redirect.github.com/opensearch-project/OpenSearch/pull/18336))
- Bump `org.apache.commons:commons-text` from 1.13.0 to 1.13.1
([#&#8203;18102](https://redirect.github.com/opensearch-project/OpenSearch/pull/18102))
- Bump `reactor-netty` from 1.2.4 to 1.2.5
([#&#8203;18243](https://redirect.github.com/opensearch-project/OpenSearch/pull/18243))
- Bump `reactor` from 3.5.20 to 3.7.5
([#&#8203;18243](https://redirect.github.com/opensearch-project/OpenSearch/pull/18243))
- Bump `com.azure:azure-core-http-netty` from 1.15.7 to 1.15.11
([#&#8203;18265](https://redirect.github.com/opensearch-project/OpenSearch/pull/18265))
- Bump `lycheeverse/lychee-action` from 2.4.0 to 2.4.1
([#&#8203;18264](https://redirect.github.com/opensearch-project/OpenSearch/pull/18264))
- Bump `com.maxmind.geoip2:geoip2` from 4.2.1 to 4.3.1
([#&#8203;18263](https://redirect.github.com/opensearch-project/OpenSearch/pull/18263),
[#&#8203;18413](https://redirect.github.com/opensearch-project/OpenSearch/pull/18413))
- Bump `com.azure:azure-json` from 1.3.0 to 1.5.0
([#&#8203;18335](https://redirect.github.com/opensearch-project/OpenSearch/pull/18335))
- Bump `org.jline:jline` from 3.29.0 to 3.30.4
([#&#8203;18368](https://redirect.github.com/opensearch-project/OpenSearch/pull/18368),
[#&#8203;18414](https://redirect.github.com/opensearch-project/OpenSearch/pull/18414))
- Bump `com.nimbusds:oauth2-oidc-sdk` from 11.23.1 to 11.25
([#&#8203;18369](https://redirect.github.com/opensearch-project/OpenSearch/pull/18369))
- Bump `gradle/actions` from 3 to 4
([#&#8203;18371](https://redirect.github.com/opensearch-project/OpenSearch/pull/18371))
- Bump `com.azure:azure-storage-common` from 12.28.0 to 12.29.0
([#&#8203;18415](https://redirect.github.com/opensearch-project/OpenSearch/pull/18415))
- Bump `com.squareup.okio:okio` from 3.10.2 to 3.12.0
([#&#8203;18468](https://redirect.github.com/opensearch-project/OpenSearch/pull/18468))
- Bump `com.azure:azure-xml` from 1.1.0 to 1.2.0
([#&#8203;18469](https://redirect.github.com/opensearch-project/OpenSearch/pull/18469))
- Bump `com.maxmind.db:maxmind-db` from 3.1.1 to 3.2.0
([#&#8203;18470](https://redirect.github.com/opensearch-project/OpenSearch/pull/18470))

##### Removed

- \[repository-s3] Removed existing ineffective `server_side_encryption`
setting
([#&#8203;18312](https://redirect.github.com/opensearch-project/OpenSearch/pull/18312))

##### Fixed

- Fix simultaneously creating a snapshot and updating the repository can
potentially trigger an infinite loop
([#&#8203;17532](https://redirect.github.com/opensearch-project/OpenSearch/pull/17532))
- Remove package org.opensearch.transport.grpc and replace with
org.opensearch.plugin.transport.grpc
([#&#8203;18031](https://redirect.github.com/opensearch-project/OpenSearch/pull/18031))
- Fix the native plugin installation error cause by the pgp public key
change
([#&#8203;18147](https://redirect.github.com/opensearch-project/OpenSearch/pull/18147))
- Fix object field exists query
([#&#8203;17843](https://redirect.github.com/opensearch-project/OpenSearch/pull/17843))
- Use Bad Request status for InputCoercionException
([#&#8203;18161](https://redirect.github.com/opensearch-project/OpenSearch/pull/18161))
- Null check field names in QueryStringQueryBuilder
([#&#8203;18194](https://redirect.github.com/opensearch-project/OpenSearch/pull/18194))
- Avoid NPE if on SnapshotInfo if 'shallow' boolean not present
([#&#8203;18187](https://redirect.github.com/opensearch-project/OpenSearch/issues/18187))
- Fix 'system call filter not installed' caused when network.host:
0.0.0.0
([#&#8203;18309](https://redirect.github.com/opensearch-project/OpenSearch/pull/18309))
- DocValues-only IP field supports `terms_query` with more than 1025 IP
masks
([#&#8203;18357](https://redirect.github.com/opensearch-project/OpenSearch/pull/18357)
- Fix MatrixStatsAggregator reuse when mode parameter changes
([#&#8203;18242](https://redirect.github.com/opensearch-project/OpenSearch/issues/18242))
- Replace the deprecated construction method of
TopScoreDocCollectorManager with the new method
([#&#8203;18395](https://redirect.github.com/opensearch-project/OpenSearch/pull/18395))
- Fixed Approximate Framework regression with Lucene 10.2.1 by updating
`intersectRight` BKD walk and `IntRef` visit method
([#&#8203;18358](https://redirect.github.com/opensearch-project/OpenSearch/issues/18358))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "on the first day of the month" (UTC),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/jaegertracing/jaeger).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS40MC4wIiwidXBkYXRlZEluVmVyIjoiNDEuNDAuMCIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOlsiY2hhbmdlbG9nOmRlcGVuZGVuY2llcyJdfQ==-->

Signed-off-by: Mend Renovate <bot@renovateapp.com>