Fix permission failed on checks-run (#5041)
## Which problem is this PR solving?
-
https://github.com/jaegertracing/jaeger/pull/5035#issuecomment-1869152935

## Description of the changes
- The logs from
https://github.com/jaegertracing/jaeger/actions/runs/7324976182/job/19949034415#step:8:67
show:
> github.GithubException.GithubException: 403 {"message": "Resource not
accessible by integration", "documentation_url":
"https://docs.github.com/rest/checks/runs#create-a-check-run"}

This is because it needs write permission on the PR check runs to
provide a summary.

- The alternative is to disable test summary in the PR checks.

## How was this change tested?
- Ran this in my fork earlier.

## Checklist
- [x] I have read
https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits

Signed-off-by: Albert Teoh <albert@packsmith.io>
Co-authored-by: Albert Teoh <albert@packsmith.io>